version: "2"
services:
        osgflockingreport:
                image: "opensciencegrid/gracc-osg-reports:osgflockingreport_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/gracc-osg-reports-config
                        - /etc/localtime:/etc/localtime
                network_mode: "host"
                command: ["-s", "${starttime}", "-e", "${endtime}", "-c", "/tmp/gracc-osg-reports-config/osg.toml", "-T", "/tmp/html_templates/template_flocking.html"]
