version: "2"
services:
        osgmissingprojectsreport:
                image: "opensciencegrid/gracc-osg-reports:osgmissingprojectsreport_${VERSIONRELEASE}"
                volumes:
                        - ${LOCALLOGDIR}:/tmp/log
                        - ${CONFIGDIR}:/tmp/gracc-osg-reports-config
                        - /etc/localtime:/etc/localtime
                network_mode: "host"
                command: ["-s", "${starttime}", "-e", "${endtime}", "-c", "/tmp/gracc-osg-reports-config/osg.toml", "-r" ,"${TYPE}"]

